language: c
before_install:
  - sudo pip install cpp-coveralls
  # backtrace support
  - sudo apt-get -y install gdb
after_success:
  - coveralls -r . -b . --exclude test --exclude sophia/std/ss_zstdfilter.c --exclude sophia/std/ss_lz4filter.c
compiler:
  - clang
  - gcc
branches:
  only:
    - master
script:
#  - make ENABLE_COVERAGE=1
#  - cd test
#  - make ENABLE_COVERAGE=1
#  - make test
#  - cd ..
